server:
  path: tasks/dev/
  port: 8080
  error.include-message: always
  debug: TRUE

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/tasks
    username: postgres
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  banner.location: classpath:banner.txt

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true

## DEV ENV
auth0.audience: "http://localhost:8080/tasks/dev/"
spring.security.oauth2.resourceserver.jwt.issuer-uri: "https://dev-9deub659.us.auth0.com/"

aws:
  secret-name: "dev/tasks/secrets"
  region: "us-east-2"